kind: ServiceAccount
apiVersion: v1
metadata:
  name: vsphere-csi-metadata-syncer
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vsphere-metadata-syncer-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vsphere-metadata-syncer-binding
subjects:
- kind: ServiceAccount
  name: vsphere-csi-metadata-syncer
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: vsphere-metadata-syncer-role
  apiGroup: rbac.authorization.k8s.io
