kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-vanilla-block-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: block.vsphere.csi.vmware.com
parameters:
  datastoreurl: "ds:///vmfs/volumes/vsan:52cdfa80721ff516-ea1e993113acfc77/" #Case insensitive optional Parameter
  storagepolicyname: "vSAN Default Storage Policy"  #Case insensitive optional Parameter
